apiVersion: v1
kind: Service
metadata:
  name: loginapp-service
spec:
  type: NodePort
  selector: 
    app: loginapp-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30004