apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp-deployment
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginapp-app

  template:
    metadata:
      name: loginapp
      labels:
        app: loginapp-app

    spec:

      containers:
        - name: loginapp
          image: vzinik/aloginapp:release
          ports:
            - containerPort: 5000

          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user          
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: postgres-secret
                    key: postgres-password
            - name: MONGO_DB
              value: 'INDRIYA'
            - name: USER_COLLECTION
              value: 'user'
            - name: DATA_COLLECTION
              value: 'data'
          